language: cpp
compiler:
  -gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script:
  - clear
  - g++ examples/hamilton/ej1.cpp -std=c++17 -o hamilton
  - g++ examples/convexo/main_convexo.cpp -std=c++17 -o convexo
  - ./hamilton < examples/hamilton/ans.txt
  - ./convexo

  # - ./t3 < examples/hamilton/ans.txt
